- name: Add www-data to User
  user:
    name: "{{ web_user }}"
    groups: www-data
    append: yes
    state: present

- name: Create new PHP-FPM pool for User
  template: 
    src: "php_fpm_user.conf.j2"
    dest: "/etc/php/{{ version }}/fpm/pool.d/{{ web_user }}.conf"
  notify: Restart_PHP-FPM

- name: Enable PHP Version in Apache
  shell: /usr/sbin/a2enmod "php{{ version }}"
  notify: Restart-Apache