- name: Sets MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: mysql_root_password_update

- name: Copy .my.cnf file with root credentials
  template:
    src: "root-my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600
  when: mysql_root_password_update

- name: Removes all anonymous user accounts
  mysql_user: 
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: mysql_secure_install

- name: Removes the test MySQL Database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: mysql_secure_install

- name: Configure MyTop
  template:
    src: "mytop_config.j2"
    dest: "/root/.mytop"
  when: mysql_root_password_update