- name: Create document root and other File structures for User
  file: 
    path: "{{ item.dest }}"
    mode: 0755
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    state: directory
  loop:
    - { dest: '/home/{{ web_user }}/{{ primary_domain }}/html' }
    - { dest: '/home/{{ web_user }}/var/{{ primary_domain }}/logs' }
    - { dest: '/home/{{ web_user }}/var/php-fpm' }

- name: Create document root and other File Structures for Secondary site
  file:
    path: "{{ item.dest }}"
    mode: 0755
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    state: directory
  loop: 
    - { dest: '/home/{{ web_user }}/{{ secondary_domain }}/html' }
    - { dest: '/home/{{ web_user }}/var/{{ secondary_domain }}/logs' }
  when: secondary_domain_update

- name: Create Symlink for Primary Domain Doc Root
  file:
    src: "/home/{{ web_user }}/{{ primary_domain }}/html"
    dest: "/home/{{ web_user }}/public_html"
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    state: link

- name: Set up Apache Virtual Host
  template:
    src: "apache_vhost.conf.j2"
    dest: "/etc/apache2/sites-available/{{ primary_domain }}.conf"
  notify: Restart-Apache

- name: Enable the New Site
  shell: /usr/sbin/a2ensite "{{ primary_domain }}"
  notify: Restart-Apache

- name: Set up Apache Virtual Host for Secondary Domain
  template:
    src: "apache_secondary_vhost.conf.j2"
    dest: "/etc/apache2/sites-available/{{ secondary_domain }}.conf"
  notify: Restart-Apache
  when: secondary_domain_update

- name: Enable Secondary Site
  shell: /usr/sbin/a2ensite "{{ secondary_domain }}"
  notify: Restart-Apache
  when: secondary_domain_update

- name: Enable Mod_Rewrite
  shell: /usr/sbin/a2enmod rewrite
  notify: Restart-Apache