- name: Add required Dependencies for libapache2-mod-security2 Backport
  apt:
    name:
      - apt-transport-https
      - lsb-release
      - ca-certificates
      - curl
    state: present
  
- name: Add Digitalwave Backport Apt key
  apt_key:
    url: https://modsecurity.digitalwave.hu/archive.key
    state: present

- name: Add Digital Wave repo to apt
  apt_repository:
    repo: "deb http://modsecurity.digitalwave.hu/ubuntu/ jammy main"
    state: present
  when: ansible_os_family == "Debian" and ansible_distribution_version == "22.04"

- name: Add Digital Wave repo backport to apt
  apt_repository:
    repo: "deb http://modsecurity.digitalwave.hu/ubuntu/ jammy-backports main"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian" and ansible_distribution_version == "22.04"

- name: Add Backport Policy
  template:
    src: 99modsecurity.j2
    dest: "/etc/apt/preferences.d/99modsecurity"
    owner: root
    group: root
    mode: 0644

# Not sure if the state being present will not reinstall backport properly
- name: Reinstall Backported libapache2-mod-security2
  apt:
    name:
      - libapache2-mod-security2
    state: present

- name: Enable Mod Security module
  shell: /usr/sbin/a2enmod security2

- name: Configure Mod Security
  template:
    src: apache_modsecurity.conf.j2
    dest: "/etc/modsecurity/modsecurity.conf"
  notify: Restart-Apache

- name: Download and Uncompress the Latest OWASP Core Rule Set (CRS)
  unarchive:
    src: "https://github.com/coreruleset/coreruleset/archive/refs/tags/v{{ default_mod_security_version }}.zip"
    dest: /tmp/
    remote_src: yes
    validate_certs: no

- name: Move the CRS file to /etc/modsecurity
  copy:
    src: "/tmp/coreruleset-{{ default_mod_security_version }}/crs-setup.conf.example"
    dest: "/etc/modsecurity/crs-setup.conf"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Move the Rules directory to /etc/modsecurity
  copy:
    src: "/tmp/coreruleset-{{ default_mod_security_version }}/rules"
    dest: "/etc/modsecurity"
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- name: Add lines to load ModSecurity rules
  template:
    src: security2.conf.j2
    dest: "/etc/apache2/mods-available/security2.conf"
  notify: Restart-Apache