# Set `default_php_version` to the version you would like PHP-CLI to run by default
default_php_version: "8.1"
php_versions:
  - "php8.0"
  - "php8.0-fpm"
  - "libapache2-mod-php8.0"
  - "php8.0-mysql"
  - "php8.0-imagick"
  - "php8.0-curl"
  - "php8.0-dom"
  - "php8.0-xml"
  - "php8.0-zip"
  - "php8.0-mbstring"
  - "php8.0-intl"
  - "php8.1"
  - "php8.1-fpm"
  - "libapache2-mod-php8.1"
  - "php8.1-mysql"
  - "php8.1-imagick"
  - "php8.1-curl"
  - "php8.1-dom"
  - "php8.1-xml"
  - "php8.1-zip"
  - "php8.1-mbstring"
  - "php8.1-intl"
  - "php8.2"
  - "php8.2-fpm"
  - "libapache2-mod-php8.2"
  - "php8.2-mysql"
  - "php8.2-imagick"
  - "php8.2-curl"
  - "php8.2-dom"
  - "php8.2-xml"
  - "php8.2-zip"
  - "php8.2-mbstring"
  - "php8.2-intl"
version: "{{ php.version | default(default_php_version) }}"