- name: Install Apache, and MariaDB Packages (Ubuntu)
  apt: 
    name: 
      - apache2 
      - libapache2-mpm-itk
      - mariadb-server
      - software-properties-common
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Start and Enable the Apache Service
  service: 
    name: apache2
    state: started
    enabled: yes

- name: Adds and Installs the ppa:ondrej/php repo to Ubuntu
  ansible.builtin.apt_repository: 
    repo: ppa:ondrej/php
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install Specific PHP Base Packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items: "{{ php_versions[0-2] }}"

- name: Install PHP-FPM Packages
  apt:
    name: "{{ php_versions[0-2] }}-{{ item }}"
    state: present
  with_items: "{{ php_fpm_packages }}"

- name: Install Apache PHP Packages
  apt:
    name: "{{ php_apache_packages }}-{{ item }}"
    state: present
  with_items: "{{ php_versions[0-2] }}"