- name: Install Apache, PHP, and MariaDB Packages (Ubuntu)
  apt: 
    name: 
      - apache2 
      - libapache2-mpm-itk
      - mariadb-server
      - php
      - php-fpm
      - libapache2-mod-php
      - php-mysql
      - software-properties-common
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Start and Enable the Apache Service
  service: 
    name: apache2
    state: started
    enabled: yes

- name: Adds and Installs the ppa:ondrej/php repo to Ubuntu
  ansible.builtin.apt_repository: 
    repo: ppa:ondrej/php
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install Specific PHP versions and Packages
  apt:
    update_cache: yes
    name:
      - "php{{ php_versions[0-2] }}"
      - "php{{ php_versions[0-2] }}-fpm"
      - "libapache2-mod-php{{ php_versions[0-2] }}"
      - "php{{ php_versions[0-2] }}-mysql"
