---

- hosts: all
  become: true
  tasks: 
    - name: Remove Apache, PHP, and MariaDB Packages (Ubuntu)
      apt: 
        name: 
          - apache2 
          - libapache2-mpm-itk
          - mariadb-server
          - php
          - php-fpm
          - libapache2-mod-php
          - php-mysql
        state: absent
      when: ansible_distribution == "Ubuntu"