---

- hosts: all
  become: true
  pre_tasks:

  - name: Update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: Install Apache, PHP, and MariaDB Packages (Ubuntu)
    apt: 
      name: 
        - apache2 
        - libapache2-mpm-itk
        - mariadb-server
        - php
        - php-fpm
        - libapache2-mod-php
        - php-mysql
      state: latest
    when: ansible_distribution == "Ubuntu"

  